import React from "react"


export const metadata = {
    title: "ISTAD - About us",
    description: "Generated by create next app",
	openGraph: {
		type: "website",
		url: `/about-us`,
		title: "ISTAD - About us",
		description: "Generated by create next app",
	},
	
  }
const page = async () => {
	
	return (
		<div className='hero min-h-screen bg-base-200'>
			
			<div className='hero-content flex-col lg:flex-row'>
				<img
					src='https://sayingimages.com/wp-content/uploads/2021/06/avengers-today-is-meme.jpg'
					className='max-w-sm rounded-lg shadow-2xl'
				/>
				<div>
					<h1 className='text-5xl font-bold'>Thor zin II</h1>
					<p className='py-6'>
						Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
						excepturi exercitationem quasi. In deleniti eaque aut repudiandae et
						a id nisi.
					</p>
					
					
				</div>
			</div>
		</div>
	)
}

export default page
